adds retries if push failed

diff --git a/.github/workflows/workflow.yaml b/.github/workflows/workflow.yaml
--- a/.github/workflows/workflow.yaml
+++ b/.github/workflows/workflow.yaml
@@ -119,15 +119,19 @@ jobs:
       - name: Commit outputs to saved_outputs branch
         if: env.should_run == 'true'
         run: |
+          set -e
           git config --global user.email "github-actions[bot]@users.noreply.github.com"
           git config --global user.name "github-actions[bot]"
+          git fetch origin saved_outputs
           git checkout saved_outputs
           git pull --rebase origin saved_outputs
           mkdir -p ${{ matrix.test-type }}-${{ env.hash }}-${{ env.general_hash }}
           cp -r ./Output/${{env.extracted_word}}/${{ matrix.test-type }} ./${{ matrix.test-type }}-${{ env.hash }}-${{ env.general_hash }}
           git add ./${{ matrix.test-type }}-${{ env.hash }}-${{ env.general_hash }}
-          git commit -m "Add ${{ matrix.test-type }}-${{ env.hash }}-${{ env.general_hash }}"
-          git push origin saved_outputs
+          git commit -m "Add ${{ matrix.test-type }}-${{ env.hash }}-${{ env.general_hash }}" || true
+
+          for i in {1..3}; do git push --force-with-lease origin saved_outputs && exit 0 || sleep 10; done
+          echo "Max retries reached, exiting with failure." && exit 1
 
       - name: Upload all
         uses: actions/upload-artifact@v3
